#!/usr/bin/env bash
# OpenMinis 仓库卫生修复 — 一键执行
# 用法：在 fork 的仓库根目录运行 bash apply-hygiene.sh
set -euo pipefail

echo "=== 1/3 追加 .gitignore 规则 ==="
cat >> .gitignore <<'GITIGNORE_EOF'

# Python bytecode — regenerated at runtime by the interpreter; never track.
# Previously committed under scripts/__pycache__/ and default_mount assets.
__pycache__/
*.pyc

# Object files from native builds — regenerated by deps/build_lame.sh etc.
# Previously committed under deps/lame-3.100/{libmp3lame,mpglib}/.
*.o
*.lo
GITIGNORE_EOF
echo "  .gitignore 追加了 __pycache__/, *.pyc, *.o, *.lo"

echo "=== 2/3 移除已追踪的构建产物 (27 .pyc + 56 .o/.lo = 83 文件) ==="
# --cached = 只从 git 索引移除，文件保留在磁盘
find . \( -name "*.pyc" -o -name "*.o" -o -name "*.lo" \) \
  -not -path "./.git/*" -print0 | \
  xargs -0 git rm --cached --quiet --
echo "  git rm --cached 完成（文件仍在磁盘，仅从索引移除）"

echo "=== 3/3 修复 README.md OkHttp 失效外链 ==="
# square.github.io/okhttp/ 返回 404 → 改指 GitHub 仓库
sed -i 's|https://square.github.io/okhttp/|https://github.com/square/okhttp|g' README.md
echo "  README.md OkHttp 链接已更新"

echo ""
echo "完成。运行 git diff --cached 查看变更，确认后 git commit。"
echo ""
echo "⚠️ 确认项：default_mount 里的 .pyc 移除后，测一次 app 冷启动"
echo "   确认 Python 运行时自动编译不依赖预存字节码。"
